apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: azure-pulumi-platform
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/rmiravalles/pulumi-automation-api
  ref:
    branch: main